-- Authentication, via Better Auth.
--
-- The five tables below are generated by `npx auth@1.7.5 generate` from
-- src/lib/auth.ts. Regenerate rather than hand-edit if the auth config gains
-- plugins or fields. Better Auth uses camelCase, quoted column names and text
-- ids; "user" must always be quoted because it's a reserved word.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

-- Replace the placeholder users table from 001 with Better Auth's "user".
-- Safe only while nothing references real accounts yet, so refuse otherwise.
do $$
begin
  if exists (select 1 from users) or exists (select 1 from records) then
    raise exception '002_auth: users or records already has rows; migrate owner ids by hand first';
  end if;
end $$;

alter table records drop constraint records_owner_user_id_fkey;
drop table users;
alter table records alter column owner_user_id type text;
alter table records
  add constraint records_owner_user_id_fkey
  foreign key (owner_user_id) references "user" ("id") on delete cascade;

create index on records (owner_user_id);
